from src.layouts.edge_exclusion_layout import edge_exclusion_layout
from src.layouts.filemanager_layout import filemanager_layout
from src.layouts.plot_settings_layout import spot_layout
from src.layouts.graph_layout import graph_layout
from src.layouts.sample_layout import outline_layout
from src.layouts.mappattern_layout import mappattern_layout
from src.layouts.stat_table_layout import stat_table_layout
from src.layouts.stage_layout import stage_layout
from src.layouts.analysis_tabs_layout import analysis_tabs_layout
